In [1]:
# Load the data into variables for experimentation
job_description_path = "api/experiments/job_description.txt"
pdf_text_path = "api/experiments/pdf_text.txt"

try:
    with open(job_description_path, 'r', encoding="utf-8") as f:
        job_text = f.read()

    with open(pdf_text_path, 'r', encoding="utf-8") as f:
        cv_text = f.read()
        
    print("✅ Files loaded successfully!")
    print(f"Job Description length: {len(job_text)} characters")
    print(f"CV Text length: {len(cv_text)} characters")

except FileNotFoundError:
    print("❌ Error: Files not found. Make sure you ran the Django view first!")

✅ Files loaded successfully!
Job Description length: 2694 characters
CV Text length: 4082 characters

In [2]:
job_text

"Product Manager (Games domain)\n- Product\n- Tel Aviv\n- Mid\n- Full-time\nDescription\nTango is a successful, market leader, a live-streaming Platform with 550+ million registered users, in an industry projected to reach $240 BILLION in the next couple of years.\nThe B2C platform, based on the best-quality global video technology, allows millions of talented people around the world to create their own live content, engage with their fans, and monetize their talents.\nTango live stream was founded in 2018 and is powered by 500+ global employees operating in a culture of growth, learning, and success!\nThe Tango team is a vigorous cocktail of hard workers, creative brains, energizers, geeks, overachievers, athletes, and more. We push the limits to bring our app from “one of the top” to “the leader”.\nThe best way to describe Tango's work style is not to use the word “impossible”. And we believe that success is a thorny path that runs on sleepless nights, corporate parties, tough releases, and, of course, our users' smiles (and as we are a LIVE app, we truly get to see our users all around the world smiling right in front of us in real-time!).\nDo you want to join the party?\nWe’re now looking for a Product Manager (Games domain) to join our Product team in Tel Aviv and take ownership of impactful, user-facing features in a fast-paced, data-driven environment.\nResponsibilities\n- Define and execute product roadmaps aligned with business goals, user needs, and company vision\n- Proactively identify new opportunities within the live-streaming ecosystem and drive product innovation\n- Own the end-to-end lifecycle of features - from ideation and prioritization to launch and post-release optimization\n- Make data-driven decisions using product analytics, user insights, and market trends\n- Define success metrics, monitor performance, and continuously iterate to improve results\n- Act as the main point of alignment between business, engineering, and stakeholders\n- Operate with a strong ship-to-production mindset, balancing speed, impact, and quality\nRequirements\n- Experience in gaming, social, or monetization-driven products (in-app purchases, virtual economies) - Must\n- 3+ years of experience as a B2C Product Manager, ideally in fast-paced tech or consumer-facing products\n- Proven track record of launching and scaling products with measurable business impact\n- Strong analytical and strategic thinking, with the ability to turn data into clear decisions\n- Excellent communication and stakeholder-management skills\n- Full professional proficiency in English (written and spoken)\n- Hands-on experience with product analytics tools (Amplitude, Mixpanel, Looker or similar)\n#LI-AP2"

In [3]:
cv_text

'Dor Lazarov\nProduct Manager with 4 years of experience\nLazamal@gmail.com\nhttps://www.linkedin.com/in/dor-lazarov-65601287\nMy Product portfolio\nTel-Aviv, Israel\n054-9732735\nSUMMARY\nProduct Manager with over 4 years of experience leading web and mobile application products in EdTech and SportTech. Skilled at working cross-\nfunctionally with developers, designers, and stakeholders to deliver user-centered products in resource-constrained environments. \nStrong background in educational and youth-focused organizations, bringing a mission-driven mindset and a hands-on approach to agile\ndevelopment. \nLooking for product management roles in a fast pace start-up company\nEXPERIENCE\nDrorsoft - Coding Your Dreams\nProduct Manager\n2025 - present\nTel-Aviv\nProduct:\nLed the product launch, development, and specification of a personal management\nsystem commissioned by a company client.\nEliminating the need for outsourced services and generating annual savings of over ₪10,000\nfor the client.\nConducted in-depth user behavior analysis and research, resulting in a 30% improvement in\nworkflow efficiency and higher tool adoption across departments.\nApplied MoSCoW prioritization and Value vs. Effort Matrix to define and scope high-impact\nfeatures, accelerating delivery time by 20% and minimizing development overhead.\nAuthored clear, developer-friendly Product Requirement Documents (PRDs), reducing back-\nand-forth communication and cutting development time by an estimated 15%.\nHanoar Haoved vehalomed - Ed-Tech & youth education\nProduct Manager\n2023-2025\nTel-Aviv\nproduct:\nLed the development of a cross-platform content management system (CMS) for youth\ninstructors, available on desktop web, iOS, and Android. Built in an agile environment\nusing Jira and Figma, user behavior is tracked via Mixpanel.\nCutting 40 admin hours/month and saving ₪8000 in monthly fees.\nManaged the full product lifecycle — from writing specifications and leading testing efforts to\noverseeing development and successful deployment of new features, contributing to a 15%\nreduction in post-deployment bugs.\n  • Overseeing sprint development meetings and collaborating with\n     developers and designers.\nHachaluz - sport organization\n“Hachaluz” is an organization that bases its sales and profits around \n Organizing community sports events using technological solutions\nJunior product manager\n2021- 2023\nTel-Aviv\nProduct:\nLed the development of a web-based app for managing community soccer leagues, including\nteam registration, scheduling, and live score tracking.\nBuilt in an Agile environment with a cross-functional team using tools like Jira, Figma, and\nimplemented tools like Google Analytics , Hotjar.  Wrote beautiful specs, planned features,\ngathered user feedback, and managed delivery across the full product lifecycle\nGenerated over 100,000 ₪ in revenue in the first year by streamlining operations and\nenhancing the user experience for league organizers and participants.\nDrove 100% year-over-year growth in product sales by leveraging user insights from\nGoogle Analytics and Hotjar to optimize features and user experience in close collaboration\nwith a cross-functional Agile team.\nDefined product strategy, wrote detailed specs, gathered user feedback, and prioritized\nfeatures—resulting in a 40% increase in user engagement and high retention across\nseasons.PASSIONS\nGamer\nSport Teams\nAs a passionate gamer,  I\npossess a solid\nunderstanding of various\nscoring and ranking\nsystems. I excel at viewing\nsituations from the\nperspectives of players,\nviewers, and other\nstakeholders.\nBasketball player\nFormer children coach\nE-Sports fan\nSKILLS\nProduct strategy | User research | Stakeholder\nManagement | Problem Solving | Product Launch\nManagment | Agile/Scrum | Jira | Figma | Confluence |\nAnalytics  | Databases | SQL | HTML CSS | JavaScript |\nPython | Roadmapping\nEDUCATION\nTechnion - Israel Institute of Technology\nProduct management\nJan 2021 - May 2021\nBeit Berl College\nBachelor of education - BEd, education\nMan 2015 -Jan 2022\nLANGUAGES\nHebrew\nNative\nEnglish\nProficient\nJapanese\nLearning'

In [4]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lazam\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
en_stopwords = stopwords.words('english')
print(en_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [6]:
df = pd.DataFrame([[job_text, cv_text]], columns=['job_text', 'cv_text'])
df['job_text_no_stopwords'] = df['job_text'].apply(lambda string: " ".join([word for word in string.split() if word not in en_stopwords]))
df['cv_text_no_stopwords'] = df['cv_text'].apply(lambda string: " ".join([word for word in string.split() if word not in en_stopwords]))
df.head()

,job_text,cv_text,job_text_no_stopwords,cv_text_no_stopwords
0,Product Manager (Games domain)\n- Product\n- T...,Dor Lazarov\nProduct Manager with 4 years of e...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...

In [7]:
punct_pattern_to_remove = r'[^\w\s]'
df['job_text_no_punct'] = df['job_text_no_stopwords'].str.replace("", "", regex=True)
df['cv_text_no_punct'] = df['cv_text_no_stopwords'].str.replace("", "", regex=True)
df.head()

,job_text,cv_text,job_text_no_stopwords,cv_text_no_stopwords,job_text_no_punct,cv_text_no_punct
0,Product Manager (Games domain)\n- Product\n- T...,Dor Lazarov\nProduct Manager with 4 years of e...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...

In [8]:
df['tokenized_job'] = df.apply(lambda x: word_tokenize(x['job_text_no_punct']), axis = 1)
df['tokenized_cv'] = df.apply(lambda x: word_tokenize(x['cv_text_no_punct']), axis = 1)
df['tokenized_job'][0]

['Product',
 'Manager',
 '(',
 'Games',
 'domain',
 ')',
 '-',
 'Product',
 '-',
 'Tel',
 'Aviv',
 '-',
 'Mid',
 '-',
 'Full-time',
 'Description',
 'Tango',
 'successful',
 ',',
 'market',
 'leader',
 ',',
 'live-streaming',
 'Platform',
 '550+',
 'million',
 'registered',
 'users',
 ',',
 'industry',
 'projected',
 'reach',
 '$',
 '240',
 'BILLION',
 'next',
 'couple',
 'years',
 '.',
 'The',
 'B2C',
 'platform',
 ',',
 'based',
 'best-quality',
 'global',
 'video',
 'technology',
 ',',
 'allows',
 'millions',
 'talented',
 'people',
 'around',
 'world',
 'create',
 'live',
 'content',
 ',',
 'engage',
 'fans',
 ',',
 'monetize',
 'talents',
 '.',
 'Tango',
 'live',
 'stream',
 'founded',
 '2018',
 'powered',
 '500+',
 'global',
 'employees',
 'operating',
 'culture',
 'growth',
 ',',
 'learning',
 ',',
 'success',
 '!',
 'The',
 'Tango',
 'team',
 'vigorous',
 'cocktail',
 'hard',
 'workers',
 ',',
 'creative',
 'brains',
 ',',
 'energizers',
 ',',
 'geeks',
 ',',
 'overachievers',
 ',',
 'athletes',
 ',',
 'more',
 '.',
 'We',
 'push',
 'limits',
 'bring',
 'app',
 '“',
 'one',
 'top',
 '”',
 '“',
 'the',
 'leader',
 '”',
 '.',
 'The',
 'best',
 'way',
 'describe',
 'Tango',
 "'s",
 'work',
 'style',
 'use',
 'word',
 '“',
 'impossible',
 '”',
 '.',
 'And',
 'believe',
 'success',
 'thorny',
 'path',
 'runs',
 'sleepless',
 'nights',
 ',',
 'corporate',
 'parties',
 ',',
 'tough',
 'releases',
 ',',
 'and',
 ',',
 'course',
 ',',
 'users',
 "'",
 'smiles',
 '(',
 'and',
 'LIVE',
 'app',
 ',',
 'truly',
 'get',
 'see',
 'users',
 'around',
 'world',
 'smiling',
 'right',
 'front',
 'us',
 'real-time',
 '!',
 ')',
 '.',
 'Do',
 'want',
 'join',
 'party',
 '?',
 'We',
 '’',
 're',
 'looking',
 'Product',
 'Manager',
 '(',
 'Games',
 'domain',
 ')',
 'join',
 'Product',
 'team',
 'Tel',
 'Aviv',
 'take',
 'ownership',
 'impactful',
 ',',
 'user-facing',
 'features',
 'fast-paced',
 ',',
 'data-driven',
 'environment',
 '.',
 'Responsibilities',
 '-',
 'Define',
 'execute',
 'product',
 'roadmaps',
 'aligned',
 'business',
 'goals',
 ',',
 'user',
 'needs',
 ',',
 'company',
 'vision',
 '-',
 'Proactively',
 'identify',
 'new',
 'opportunities',
 'within',
 'live-streaming',
 'ecosystem',
 'drive',
 'product',
 'innovation',
 '-',
 'Own',
 'end-to-end',
 'lifecycle',
 'features',
 '-',
 'ideation',
 'prioritization',
 'launch',
 'post-release',
 'optimization',
 '-',
 'Make',
 'data-driven',
 'decisions',
 'using',
 'product',
 'analytics',
 ',',
 'user',
 'insights',
 ',',
 'market',
 'trends',
 '-',
 'Define',
 'success',
 'metrics',
 ',',
 'monitor',
 'performance',
 ',',
 'continuously',
 'iterate',
 'improve',
 'results',
 '-',
 'Act',
 'main',
 'point',
 'alignment',
 'business',
 ',',
 'engineering',
 ',',
 'stakeholders',
 '-',
 'Operate',
 'strong',
 'ship-to-production',
 'mindset',
 ',',
 'balancing',
 'speed',
 ',',
 'impact',
 ',',
 'quality',
 'Requirements',
 '-',
 'Experience',
 'gaming',
 ',',
 'social',
 ',',
 'monetization-driven',
 'products',
 '(',
 'in-app',
 'purchases',
 ',',
 'virtual',
 'economies',
 ')',
 '-',
 'Must',
 '-',
 '3+',
 'years',
 'experience',
 'B2C',
 'Product',
 'Manager',
 ',',
 'ideally',
 'fast-paced',
 'tech',
 'consumer-facing',
 'products',
 '-',
 'Proven',
 'track',
 'record',
 'launching',
 'scaling',
 'products',
 'measurable',
 'business',
 'impact',
 '-',
 'Strong',
 'analytical',
 'strategic',
 'thinking',
 ',',
 'ability',
 'turn',
 'data',
 'clear',
 'decisions',
 '-',
 'Excellent',
 'communication',
 'stakeholder-management',
 'skills',
 '-',
 'Full',
 'professional',
 'proficiency',
 'English',
 '(',
 'written',
 'spoken',
 ')',
 '-',
 'Hands-on',
 'experience',
 'product',
 'analytics',
 'tools',
 '(',
 'Amplitude',
 ',',
 'Mixpanel',
 ',',
 'Looker',
 'similar',
 ')',
 '#',
 'LI-AP2']

In [9]:
ps = PorterStemmer()
df['stemmed_job'] = df['tokenized_job'].apply(lambda tokens: [ps.stem(token) for token in tokens])
df['stemmed_cv'] = df['tokenized_cv'].apply(lambda tokens: [ps.stem(token) for token in tokens])
df.head()

,job_text,cv_text,job_text_no_stopwords,cv_text_no_stopwords,job_text_no_punct,cv_text_no_punct,tokenized_job,tokenized_cv,stemmed_job,stemmed_cv
0,Product Manager (Games domain)\n- Product\n- T...,Dor Lazarov\nProduct Manager with 4 years of e...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...,"[Product, Manager, (, Games, domain, ), -, Pro...","[Dor, Lazarov, Product, Manager, 4, years, exp...","[product, manag, (, game, domain, ), -, produc...","[dor, lazarov, product, manag, 4, year, experi..."

In [10]:
lemmatizer = WordNetLemmatizer()
df['lemmatized_job'] = df['tokenized_job'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
df['lemmatized_cv'] = df['tokenized_cv'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
df.head()

,job_text,cv_text,job_text_no_stopwords,cv_text_no_stopwords,job_text_no_punct,cv_text_no_punct,tokenized_job,tokenized_cv,stemmed_job,stemmed_cv,lemmatized_job,lemmatized_cv
0,Product Manager (Games domain)\n- Product\n- T...,Dor Lazarov\nProduct Manager with 4 years of e...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...,Product Manager (Games domain) - Product - Tel...,Dor Lazarov Product Manager 4 years experience...,"[Product, Manager, (, Games, domain, ), -, Pro...","[Dor, Lazarov, Product, Manager, 4, years, exp...","[product, manag, (, game, domain, ), -, produc...","[dor, lazarov, product, manag, 4, year, experi...","[Product, Manager, (, Games, domain, ), -, Pro...","[Dor, Lazarov, Product, Manager, 4, year, expe..."

In [11]:
job_tokens_clean =  sum(df['lemmatized_job'], [])
cv_tokens_clean =  sum(df['lemmatized_cv'], [])

In [12]:

job_unigrams = pd.Series(nltk.ngrams(job_tokens_clean, 1)).value_counts()
job_unigrams

(,,)           41
(-,)           20
(.,)            7
(product,)      7
((,)            6
               ..
(Mixpanel,)     1
(Looker,)       1
(similar,)      1
(#,)            1
(LI-AP2,)       1
Name: count, Length: 236, dtype: int64

In [13]:
cv_unigrams = pd.Series(nltk.ngrams(cv_tokens_clean, 1)).value_counts()
cv_unigrams

(,,)             31
(.,)             19
(|,)             15
(Product,)       11
(product,)       10
                 ..
(Native,)         1
(English,)        1
(Proficient,)     1
(Japanese,)       1
(Learning,)       1
Name: count, Length: 318, dtype: int64

In [14]:
job_bigrams = pd.Series(nltk.ngrams(job_tokens_clean, 2)).value_counts()
job_bigrams

(Product, Manager)    3
(), -)                3
(,, user)             3
(Manager, ()          2
((, Games)            2
                     ..
(,, Looker)           1
(Looker, similar)     1
(similar, ))          1
(), #)                1
(#, LI-AP2)           1
Name: count, Length: 351, dtype: int64

In [15]:
cv_bigrams = pd.Series(nltk.ngrams(cv_tokens_clean, 2)).value_counts()
cv_bigrams

(Product, Manager)        4
(:, Led)                  3
(feature, ,)              3
(Manager, 4)              2
(4, year)                 2
                         ..
(Hebrew, Native)          1
(Native, English)         1
(English, Proficient)     1
(Proficient, Japanese)    1
(Japanese, Learning)      1
Name: count, Length: 481, dtype: int64

In [16]:
job_ngrams = pd.Series(nltk.ngrams(job_tokens_clean, 3)).value_counts()
job_ngrams

(Product, Manager, ()    2
(Manager, (, Games)      2
((, Games, domain)       2
(Games, domain, ))       2
(domain, ), -)           1
                        ..
(Mixpanel, ,, Looker)    1
(,, Looker, similar)     1
(Looker, similar, ))     1
(similar, ), #)          1
(), #, LI-AP2)           1
Name: count, Length: 363, dtype: int64

In [17]:
cv_ngrams = pd.Series(nltk.ngrams(cv_tokens_clean, 3)).value_counts()
cv_ngrams

(Product, Manager, 4)               2
(Manager, 4, year)                  2
(4, year, experience)               2
(Tel-Aviv, Product, :)              2
(Product, :, Led)                   2
                                   ..
(LANGUAGES, Hebrew, Native)         1
(Hebrew, Native, English)           1
(Native, English, Proficient)       1
(English, Proficient, Japanese)     1
(Proficient, Japanese, Learning)    1
Name: count, Length: 500, dtype: int64

In [18]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [19]:
job_tokens_string = " ".join(job_tokens_clean)
cv_tokens_string = " ".join(cv_tokens_clean)

job_spacy_doc = nlp(job_tokens_string)
cv_spacy_doc = nlp(cv_tokens_string)

job_pos_df = pd.DataFrame(columns = ['token', 'pos_tag'])
cv_pos_df= pd.DataFrame(columns = ['token', 'pos_tag'])

In [20]:
print(job_spacy_doc)

Product Manager ( Games domain ) - Product - Tel Aviv - Mid - Full-time Description Tango successful , market leader , live-streaming Platform 550+ million registered user , industry projected reach $ 240 BILLION next couple year . The B2C platform , based best-quality global video technology , allows million talented people around world create live content , engage fan , monetize talent . Tango live stream founded 2018 powered 500+ global employee operating culture growth , learning , success ! The Tango team vigorous cocktail hard worker , creative brain , energizer , geek , overachiever , athlete , more . We push limit bring app “ one top ” “ the leader ” . The best way describe Tango 's work style use word “ impossible ” . And believe success thorny path run sleepless night , corporate party , tough release , and , course , user ' smile ( and LIVE app , truly get see user around world smiling right front u real-time ! ) . Do want join party ? We ’ re looking Product Manager ( Games domain ) join Product team Tel Aviv take ownership impactful , user-facing feature fast-paced , data-driven environment . Responsibilities - Define execute product roadmaps aligned business goal , user need , company vision - Proactively identify new opportunity within live-streaming ecosystem drive product innovation - Own end-to-end lifecycle feature - ideation prioritization launch post-release optimization - Make data-driven decision using product analytics , user insight , market trend - Define success metric , monitor performance , continuously iterate improve result - Act main point alignment business , engineering , stakeholder - Operate strong ship-to-production mindset , balancing speed , impact , quality Requirements - Experience gaming , social , monetization-driven product ( in-app purchase , virtual economy ) - Must - 3+ year experience B2C Product Manager , ideally fast-paced tech consumer-facing product - Proven track record launching scaling product measurable business impact - Strong analytical strategic thinking , ability turn data clear decision - Excellent communication stakeholder-management skill - Full professional proficiency English ( written spoken ) - Hands-on experience product analytics tool ( Amplitude , Mixpanel , Looker similar ) # LI-AP2

In [21]:
print(cv_spacy_doc)

Dor Lazarov Product Manager 4 year experience Lazamal @ gmail.com http : //www.linkedin.com/in/dor-lazarov-65601287 My Product portfolio Tel-Aviv , Israel 054-9732735 SUMMARY Product Manager 4 year experience leading web mobile application product EdTech SportTech . Skilled working cross- functionally developer , designer , stakeholder deliver user-centered product resource-constrained environment . Strong background educational youth-focused organization , bringing mission-driven mindset hands-on approach agile development . Looking product management role fast pace start-up company EXPERIENCE Drorsoft - Coding Your Dreams Product Manager 2025 - present Tel-Aviv Product : Led product launch , development , specification personal management system commissioned company client . Eliminating need outsourced service generating annual saving ₪10,000 client . Conducted in-depth user behavior analysis research , resulting 30 % improvement workflow efficiency higher tool adoption across department . Applied MoSCoW prioritization Value vs. Effort Matrix define scope high-impact feature , accelerating delivery time 20 % minimizing development overhead . Authored clear , developer-friendly Product Requirement Documents ( PRDs ) , reducing back- and-forth communication cutting development time estimated 15 % . Hanoar Haoved vehalomed - Ed-Tech & youth education Product Manager 2023-2025 Tel-Aviv product : Led development cross-platform content management system ( CMS ) youth instructor , available desktop web , iOS , Android . Built agile environment using Jira Figma , user behavior tracked via Mixpanel . Cutting 40 admin hours/month saving ₪8000 monthly fee . Managed full product lifecycle — writing specification leading testing effort overseeing development successful deployment new feature , contributing 15 % reduction post-deployment bug . • Overseeing sprint development meeting collaborating developer designer . Hachaluz - sport organization “ Hachaluz ” organization base sale profit around Organizing community sport event using technological solution Junior product manager 2021- 2023 Tel-Aviv Product : Led development web-based app managing community soccer league , including team registration , scheduling , live score tracking . Built Agile environment cross-functional team using tool like Jira , Figma , implemented tool like Google Analytics , Hotjar . Wrote beautiful spec , planned feature , gathered user feedback , managed delivery across full product lifecycle Generated 100,000 ₪ revenue first year streamlining operation enhancing user experience league organizer participant . Drove 100 % year-over-year growth product sale leveraging user insight Google Analytics Hotjar optimize feature user experience close collaboration cross-functional Agile team . Defined product strategy , wrote detailed spec , gathered user feedback , prioritized feature — resulting 40 % increase user engagement high retention across seasons.PASSIONS Gamer Sport Teams As passionate gamer , I possess solid understanding various scoring ranking system . I excel viewing situation perspective player , viewer , stakeholder . Basketball player Former child coach E-Sports fan SKILLS Product strategy | User research | Stakeholder Management | Problem Solving | Product Launch Managment | Agile/Scrum | Jira | Figma | Confluence | Analytics | Databases | SQL | HTML CSS | JavaScript | Python | Roadmapping EDUCATION Technion - Israel Institute Technology Product management Jan 2021 - May 2021 Beit Berl College Bachelor education - BEd , education Man 2015 -Jan 2022 LANGUAGES Hebrew Native English Proficient Japanese Learning

In [22]:
job_pos_df.head()

Empty DataFrame
Columns: [token, pos_tag]
Index: []

In [23]:
for token in job_spacy_doc:
    job_pos_df = pd.concat([job_pos_df,
                           pd.DataFrame.from_records([{'token': token.text, 'pos_tag':token.pos_}])], ignore_index = True)

In [24]:
for token in cv_spacy_doc:
    cv_pos_df = pd.concat([cv_pos_df,
                           pd.DataFrame.from_records([{'token': token.text, 'pos_tag':token.pos_}])], ignore_index = True)

In [25]:
job_pos_df.head(15)

      token pos_tag
0   Product   PROPN
1   Manager   PROPN
2         (   PUNCT
3     Games   PROPN
4    domain    NOUN
5         )   PUNCT
6         -   PUNCT
7   Product    NOUN
8         -   PUNCT
9       Tel   PROPN
10     Aviv   PROPN
11        -   PUNCT
12      Mid   PROPN
13        -   PUNCT
14     Full     ADJ

In [26]:
job_pos_df_count = job_pos_df.groupby(['token', 'pos_tag']).size().reset_index(name="counts").sort_values(by="counts", ascending= False)
cv_pos_df_count = cv_pos_df.groupby(['token', 'pos_tag']).size().reset_index(name="counts").sort_values(by="counts", ascending= False)
job_pos_df_count.head(15)

        token pos_tag  counts
9           ,   PUNCT      41
11          -   PUNCT      40
12          .   PUNCT       7
172   product    NOUN       7
5           (   PUNCT       6
6           )   PUNCT       6
230      user    NOUN       6
53      Tango   PROPN       4
55        The     DET       3
87       data    NOUN       3
73   business    NOUN       3
64        app    NOUN       3
92     driven    VERB       3
208   success    NOUN       3
39    Manager   PROPN       3

In [27]:
cv_pos_df_count.head(15)

           token pos_tag  counts
4              ,   PUNCT      31
7              -   PUNCT      26
10             .   PUNCT      20
335            |    NOUN      14
276      product    NOUN      10
320         user    NOUN       9
187  development    NOUN       8
0              %    NOUN       6
113      Product   PROPN       6
333         year    NOUN       5
112      Product    NOUN       5
203      feature    NOUN       5
5              -     ADJ       4
99       Manager   PROPN       4
40          Aviv   PROPN       4

In [28]:
from spacy import displacy
from spacy import tokenizer
from IPython.display import HTML, display

In [29]:
for word in job_spacy_doc.ents:
    print(word.text, word.label_)

Description Tango PERSON
Platform 550+ million PRODUCT
$ 240 BILLION MONEY
next couple year DATE
million CARDINAL
2018 DATE
500 CARDINAL
Tango ORG
Tango ORG
sleepless night TIME
Tel Aviv GPE
3+ year DATE
English LANGUAGE
Amplitude , Mixpanel WORK_OF_ART
Looker ORG
LI-AP2 ORG

In [30]:
for word in cv_spacy_doc.ents:
    print(word.text, word.label_)

4 year DATE
Lazamal ORG
Tel-Aviv GPE
Israel GPE
4 year DATE
EdTech ORG
SportTech PRODUCT
Drorsoft - Coding Your Dreams ORG
2025 DATE
Tel-Aviv GPE
annual DATE
10,000 CARDINAL
30 % PERCENT
Value PERSON
20 % PERCENT
Product Requirement Documents ORG
15 % PERCENT
Hanoar Haoved PERSON
- Ed-Tech & PERSON
2023-2025 DATE
Tel-Aviv GPE
CMS ORG
Android ORG
Jira Figma PERSON
40 admin hours TIME
monthly DATE
15 % PERCENT
Hachaluz - sport PERSON
Hachaluz WORK_OF_ART
Organizing NORP
2023 DATE
Tel-Aviv ORG
Jira PERSON
Figma ORG
Google Analytics ORG
Hotjar GPE
100,000 CARDINAL
first year DATE
100 % PERCENT
Google Analytics Hotjar ORG
Agile NORP
40 % PERCENT
Gamer Sport Teams PERSON
E-Sports ORG
Stakeholder Management ORG
Problem Solving PERSON
Product Launch Managment ORG
Jira PERSON
Figma ORG
SQL ORG
HTML CSS ORG
JavaScript ORG
Jan 2021 - May 2021 DATE
Beit Berl College Bachelor ORG
Man 2015 DATE
Hebrew Native NORP
English NORP

In [31]:
html = displacy.render(job_spacy_doc, style="ent", jupyter = False)
display(HTML(html))

In [46]:
html = displacy.render(cv_spacy_doc, style="ent", jupyter = False)
display(HTML(html))

In [48]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
countvec = CountVectorizer()

In [38]:
text_array = [job_text,cv_text]

countvec_fit = countvec.fit_transform(text_array)

In [40]:
bag_of_words = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out())

In [47]:
print(bag_of_words)

   000  054  10  100  15  20  2015  2018  2021  2022  ...  world  writing  \
0    0    0   0    0   0   0     0     1     0     0  ...      2        0
1    2    1   1    2   2   1     1     0     3     1  ...      0        1

   written  wrote  www  year  years  you  your  youth
0        1      0    0     0      2    1     0      0
1        0      2    1     3      2    0     1      3

[2 rows x 502 columns]

In [53]:
tfidfvec = TfidfVectorizer()
tfidfvec_fit = tfidfvec.fit_transform(text_array)
tfidf_bag = pd.DataFrame(tfidfvec_fit.toarray(), columns = tfidfvec.get_feature_names_out())
print(tfidf_bag)
tfidf_bag.head(15)

        000       054        10       100        15        20      2015  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
1  0.046574  0.023287  0.023287  0.046574  0.046574  0.023287  0.023287

       2018      2021      2022  ...     world   writing   written     wrote  \
0  0.030103  0.000000  0.000000  ...  0.060205  0.000000  0.030103  0.000000
1  0.000000  0.069861  0.023287  ...  0.000000  0.023287  0.000000  0.046574

        www      year     years       you      your     youth
0  0.000000  0.000000  0.042837  0.030103  0.000000  0.000000
1  0.023287  0.069861  0.033138  0.000000  0.023287  0.069861

[2 rows x 502 columns]

,000,054,10,100,15,20,2015,2018,2021,2022,...,world,writing,written,wrote,www,year,years,you,your,youth
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030103,0.000000,0.000000,...,0.060205,0.000000,0.030103,0.000000,0.000000,0.000000,0.042837,0.030103,0.000000,0.000000
1,0.046574,0.023287,0.023287,0.046574,0.046574,0.023287,0.023287,0.000000,0.069861,0.023287,...,0.000000,0.023287,0.000000,0.046574,0.023287,0.069861,0.033138,0.000000,0.023287,0.069861